version: '3.5'

services:
   front:
      build: ./frontend
      ports:
        - 5000:5000
      container_name: frontend
   back:
      build: ./backend
      environment:
        - REDIS=192.168.0.115
        - REDIS_PORT=6379
      ports:
        - 8888:8000
      volumes:
        - ./logs.txt:/usr/app/logs.txt
      container_name: backend
   redis:
      image: redis
      ports:
        - 6379:6379 