version: '3.5'

services:
   front:
      build: ./frontend
      ports:
        - 5000:5000
      container_name: frontend
   back:
      build: ./backend
      environment:
        - REDIS=192.168.0.117
        - REDIS_PORT=6379
        - DB_USERNAME=dbuser
        - DB_PASSWORD=dbpass
        - DB_NAME=postgres
        - DB_HOST=db
      ports:
        - 8888:8000
      volumes:
        - ./logs.txt:/usr/app/logs.txt
      container_name: backend
      depends_on:
        - db
   redis:
      image: redis
      ports:
        - 6379:6379
      volumes:
        - ./data:/data
   proxy:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - front
        - back
   db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: dbuser
        POSTGRES_PASSWORD: dbpass
        POSTGRES_DB: postgres
      volumes:
        - ./database:/var/lib/postgresql/data